"""initial migration

Revision ID: 049511daa698
Revises: 
Create Date: 2025-04-21 16:51:32.078140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '049511daa698'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Adresse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetname', sa.String(length=225), nullable=True),
    sa.Column('streetnumber', sa.Integer(), nullable=True),
    sa.Column('postalcode', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Adresse_id'), 'Adresse', ['id'], unique=False)
    op.create_index(op.f('ix_Adresse_streetname'), 'Adresse', ['streetname'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=225), nullable=True),
    sa.Column('Number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=True),
    sa.Column('city', sa.String(length=225), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.drop_index('ix_Users_id', table_name='users')
    op.drop_index('ix_Users_name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Users_name', 'users', ['name'], unique=False)
    op.create_index('ix_Users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Adresse_streetname'), table_name='Adresse')
    op.drop_index(op.f('ix_Adresse_id'), table_name='Adresse')
    op.drop_table('Adresse')
    # ### end Alembic commands ###
