"""4 migration

Revision ID: 05d8508965c1
Revises: 670eabbb4a54
Create Date: 2025-04-21 17:54:29.605886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05d8508965c1'
down_revision: Union[str, None] = '670eabbb4a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('adresse', sa.Column('streetName', sa.String(length=225), nullable=True))
    op.add_column('adresse', sa.Column('streetNumber', sa.Integer(), nullable=True))
    op.add_column('adresse', sa.Column('postalCode', sa.Integer(), nullable=True))
    op.add_column('adresse', sa.Column('city', sa.String(length=225), nullable=True))
    op.drop_index('ix_Adresse_id', table_name='adresse')
    op.drop_index('ix_Adresse_streetname', table_name='adresse')
    op.create_index(op.f('ix_adresse_id'), 'adresse', ['id'], unique=False)
    op.create_index(op.f('ix_adresse_streetName'), 'adresse', ['streetName'], unique=False)
    op.drop_column('adresse', 'streetname')
    op.drop_column('adresse', 'postalcode')
    op.drop_column('adresse', 'streetnumber')
    op.add_column('hotels', sa.Column('adresse_id', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('suitesNumber', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('doubleRoomNumber', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('simpleRoomNumber', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('Description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'hotels', 'adresse', ['adresse_id'], ['id'])
    op.drop_column('hotels', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('city', mysql.VARCHAR(length=225), nullable=True))
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'Description')
    op.drop_column('hotels', 'simpleRoomNumber')
    op.drop_column('hotels', 'doubleRoomNumber')
    op.drop_column('hotels', 'suitesNumber')
    op.drop_column('hotels', 'adresse_id')
    op.add_column('adresse', sa.Column('streetnumber', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('adresse', sa.Column('postalcode', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('adresse', sa.Column('streetname', mysql.VARCHAR(length=225), nullable=True))
    op.drop_index(op.f('ix_adresse_streetName'), table_name='adresse')
    op.drop_index(op.f('ix_adresse_id'), table_name='adresse')
    op.create_index('ix_Adresse_streetname', 'adresse', ['streetname'], unique=False)
    op.create_index('ix_Adresse_id', 'adresse', ['id'], unique=False)
    op.drop_column('adresse', 'city')
    op.drop_column('adresse', 'postalCode')
    op.drop_column('adresse', 'streetNumber')
    op.drop_column('adresse', 'streetName')
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Users_name', 'users', ['name'], unique=False)
    op.create_index('ix_Users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
