"""mig 7

Revision ID: 0e92bbe9538e
Revises: 9c6c03c24dd5
Create Date: 2025-04-24 11:37:06.099512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e92bbe9538e'
down_revision: Union[str, None] = '9c6c03c24dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolesAcl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.String(length=225), nullable=True),
    sa.Column('id_Task', sa.String(length=225), nullable=True),
    sa.Column('Permission', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolesAcl_id'), 'rolesAcl', ['id'], unique=False)
    op.create_index(op.f('ix_rolesAcl_id_Task'), 'rolesAcl', ['id_Task'], unique=False)
    op.create_index(op.f('ix_rolesAcl_id_role'), 'rolesAcl', ['id_role'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_rolesAcl_id_role'), table_name='rolesAcl')
    op.drop_index(op.f('ix_rolesAcl_id_Task'), table_name='rolesAcl')
    op.drop_index(op.f('ix_rolesAcl_id'), table_name='rolesAcl')
    op.drop_table('rolesAcl')
    # ### end Alembic commands ###
