"""2  migration

Revision ID: 584c045f47aa
Revises: 049511daa698
Create Date: 2025-04-21 16:56:07.661178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '584c045f47aa'
down_revision: Union[str, None] = '049511daa698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=225), nullable=True),
    sa.Column('Number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=False)
    
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.drop_index('ix_Adresse_id', table_name='adresse')
    op.drop_index('ix_Adresse_streetname', table_name='adresse')
    op.drop_table('adresse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresse',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('streetname', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('streetnumber', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('postalcode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', mysql.VARCHAR(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Adresse_streetname', 'adresse', ['streetname'], unique=False)
    op.create_index('ix_Adresse_id', 'adresse', ['id'], unique=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Adresse_streetname'), table_name='Adresse')
    op.drop_index(op.f('ix_Adresse_id'), table_name='Adresse')
    op.drop_table('Adresse')
    # ### end Alembic commands ###
