"""4 migration

Revision ID: 68a65c345cd2
Revises: 05d8508965c1
Create Date: 2025-04-21 17:56:57.813878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68a65c345cd2'
down_revision: Union[str, None] = '05d8508965c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adresse', sa.Column('streetName', sa.String(length=225), nullable=True))
    op.add_column('adresse', sa.Column('streetNumber', sa.Integer(), nullable=True))
    op.add_column('adresse', sa.Column('postalCode', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_adresse_streetName'), 'adresse', ['streetName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adresse_streetName'), table_name='adresse')
    op.drop_column('adresse', 'postalCode')
    op.drop_column('adresse', 'streetNumber')
    op.drop_column('adresse', 'streetName')
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Users_name', 'users', ['name'], unique=False)
    op.create_index('ix_Users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
