"""migration 5

Revision ID: 6b16d5153495
Revises: 68a65c345cd2
Create Date: 2025-04-23 00:17:43.622444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b16d5153495'
down_revision: Union[str, None] = '68a65c345cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('Description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('adresse', sa.String(length=225), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=225), nullable=True))
    op.drop_index('ix_Users_id', table_name='users')
    op.drop_index('ix_Users_name', table_name='users')
    op.create_index(op.f('ix_users_adresse'), 'users', ['adresse'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_column('users', 'Age')
    op.drop_column('users', 'Number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('Age', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_adresse'), table_name='users')
    op.create_index('ix_Users_name', 'users', ['name'], unique=False)
    op.create_index('ix_Users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'adresse')
    op.drop_column('roles', 'Description')
    # ### end Alembic commands ###
