"""migration 11

Revision ID: 82ffc2035b3c
Revises: 1a707b2b9c6f
Create Date: 2025-04-25 12:13:25.828077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82ffc2035b3c'
down_revision: Union[str, None] = '1a707b2b9c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolesacl', sa.Column('id_task', sa.Integer(), nullable=True))
    op.add_column('rolesacl', sa.Column('permission', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_rolesacl_id'), 'rolesacl', ['id'], unique=False)
    op.drop_column('rolesacl', 'Permission')
    op.drop_column('rolesacl', 'id_Task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolesacl', sa.Column('id_Task', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rolesacl', sa.Column('Permission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_rolesacl_id'), table_name='rolesacl')
    op.drop_column('rolesacl', 'permission')
    op.drop_column('rolesacl', 'id_task')
    # ### end Alembic commands ###
