"""migration 6

Revision ID: 9c6c03c24dd5
Revises: a423f013c67f
Create Date: 2025-04-24 10:47:46.144926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6c03c24dd5'
down_revision: Union[str, None] = 'a423f013c67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_acl',
    sa.Column('id_Role', sa.Integer(), nullable=False),
    sa.Column('id_Task', sa.String(length=225), nullable=False),
    sa.Column('permission', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_Role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id_Role', 'id_Task')
    )
    op.drop_index('ix_roles_id', table_name='roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.drop_table('role_acl')
    # ### end Alembic commands ###
