"""migration 16

Revision ID: a61bba160a8c
Revises: e0815ed79da6
Create Date: 2025-04-25 13:19:05.184912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a61bba160a8c'
down_revision: Union[str, None] = 'e0815ed79da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('booking_reference_number', sa.Integer(), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=True),
    sa.Column('check_out_date', sa.Date(), nullable=True),
    sa.Column('number_of_guests', sa.Integer(), nullable=True),
    sa.Column('id_type', sa.String(length=255), nullable=True),
    sa.Column('id_number', sa.Integer(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.Integer(), nullable=True),
    sa.Column('requests', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('room_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.add_column('rolesacl', sa.Column('id_task', sa.Integer(), nullable=True))
    op.add_column('rolesacl', sa.Column('permission', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_rolesacl_id'), 'rolesacl', ['id'], unique=False)
    op.drop_column('rolesacl', 'Permission')
    op.drop_column('rolesacl', 'id_Task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolesacl', sa.Column('id_Task', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rolesacl', sa.Column('Permission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_rolesacl_id'), table_name='rolesacl')
    op.drop_column('rolesacl', 'permission')
    op.drop_column('rolesacl', 'id_task')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
