"""migration 10

Revision ID: bd0cd0af5c0a
Revises: 82ffc2035b3c
Create Date: 2025-04-25 12:20:03.733310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd0cd0af5c0a'
down_revision: Union[str, None] = '82ffc2035b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.add_column('rolesacl', sa.Column('id_task', sa.Integer(), nullable=True))
    op.add_column('rolesacl', sa.Column('permission', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_rolesacl_id'), 'rolesacl', ['id'], unique=False)
    op.drop_column('rolesacl', 'id_Task')
    op.drop_column('rolesacl', 'Permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolesacl', sa.Column('Permission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('rolesacl', sa.Column('id_Task', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_rolesacl_id'), table_name='rolesacl')
    op.drop_column('rolesacl', 'permission')
    op.drop_column('rolesacl', 'id_task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
