"""mig 8

Revision ID: fd00fb369a63
Revises: 0e92bbe9538e
Create Date: 2025-04-24 11:44:45.219022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd00fb369a63'
down_revision: Union[str, None] = '0e92bbe9538e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolesAcl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_Task', sa.Integer(), nullable=True),
    sa.Column('Permission', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolesAcl_id'), 'rolesAcl', ['id'], unique=False)
    op.drop_index('ix_rolesAcl_id', table_name='rolesacl')
    op.drop_index('ix_rolesAcl_id_Task', table_name='rolesacl')
    op.drop_index('ix_rolesAcl_id_role', table_name='rolesacl')
    op.drop_table('rolesacl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolesacl',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_role', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('id_Task', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Permission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rolesAcl_id_role', 'rolesacl', ['id_role'], unique=False)
    op.create_index('ix_rolesAcl_id_Task', 'rolesacl', ['id_Task'], unique=False)
    op.create_index('ix_rolesAcl_id', 'rolesacl', ['id'], unique=False)
    op.drop_index(op.f('ix_rolesAcl_id'), table_name='rolesAcl')
    op.drop_table('rolesAcl')
    # ### end Alembic commands ###
